name: Auto publish ZH
on:
  pull_request: {}
  push:
    paths:
      - index-zh.html
    branches: [main]
jobs:
  main:
    name: Build, Validate and Deploy
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: w3c/spec-prod@v2
        with:
          SOURCE: index-zh.html
          GH_PAGES_BRANCH: gh-pages
          TOOLCHAIN: respec
